### PR TITLE
enable override of node properties and clean up codegen template 

### PR DESCRIPTION
**Pull request by rbordeanu**
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Proposed changes

This change enables to externaly override node properties (i.e. on the incoming msg).
It also allows for mustache templating on the node property (i.e. use {{attribute}} in the node UI to explicitly reference a msg attribute).

I also cleaned up the code generation template in case of 'body' parameter, to reduce code clutter and make the generated code a bit more intuitive for human reading.

## Checklist
_Put an `x` in the boxes that apply_

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by rbordeanu** [comment]
[slight off-topic]: Any idea why my identation on the commit seems messed up?
I'm using VS Code for editing and it looks fine on my side.

**Comment by t-ide** [comment]
> rbordeanu
Probably you have to use spaces instead of tab as indentation.　
You can use "editor.detectIndentation" option in VSCode settings. https://code.visualstudio.com/docs/getstarted/settings

**Comment by knolleary** [comment]
We don’t do mustache templating in general - and I am not in favour of adding it here.
The http request url field is a rare exception - we added it very early on in node-red and can't now remove it. It is useful in that instance because you do often want to template the url - ie substitute just part of it with a msg property.

But if you just want to set a node property to the value of a msg property, then we’d normally now use a TypedInput that lets you pick a `msg.` property, or select `string` type and enter the desired value.

**Comment by rbordeanu** [comment]
I updated the PR according to the recommendation from @knolleary (i.e changed param fields to typedInput) + added more helpers for code generation

**Comment by kazuhitoyokoi** [comment]
@t-ide Thank you for your help.
@knolleary Thank you for your recommendation about typedInput. I learned the design of Node-RED. 
@rbordeanu I checked your code. And I generated and tested swagger node using petstore swagger definition. It looks great. 💯

typedinput

@HiroyasuNishiyama Could you merge this pull request?

**Comment by rbordeanu** [comment]
I had to ammend the PR because the naive way of retrieving msg property was not working for nested properties (msg.a.b.c).
Fixed using the correct method now, which is RED.util.getMessageProperty.

**Comment by kazuhitoyokoi** [comment]
@HiroyasuNishiyama Thank you. 👍

**Pull request merged**
