### PR TITLE
Use petstore on docker instead of petstore.swagger.io

### PR DESCRIPTION
**Pull request by HirokiUchikawa**
## Types of changes
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes
Currently test cases for petstore use http://petstore.swagger.io .
I changed it to use petstore on docker on travis. 
and I removed node.js v7 from travis because node.js v7 is not LTS.

## Checklist
- [X] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [X] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by kazuhitoyokoi** [comment]
@HirokiUchikawa 
Thank you for the pull request. It will be useful to test various version of Node.js simultaneously because swagger petstore server has status.

I checked docker version of petstore server. The value of "host" in swagger.json is "localhost:8002". 
Therefore, I think that the followings are correct settings.

(1) hosts configuration is not required.
```
-  hosts:
 -    - petstore.swagger.io
```

(2) SWAGGER_HOST value in docker run command is not required.
(3) Port number of docker instance is "8002".
```
-  - docker run -d -e SWAGGER_HOST=http://petstore.swagger.io -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore
+  - docker run -d -e SWAGGER_BASE_PATH=/v2 -p 8002:8080 swaggerapi/petstore
```

Could you check the settings?

**Comment by HirokiUchikawa** [comment]
@kazuhitoyokoi
Thank you for the feedback.
I will check  the settings and fix my pull request.

**Comment by HirokiUchikawa** [comment]
@kazuhitoyokoi
I investigated this problem and found the cause.

This [website](https://hub.docker.com/r/swaggerapi/petstore/) says that the host is set by `SWAGGER_HOST`.
But Actually the host is set by `SWAGGER_URL` in Docker.
So I will replace `SWAGGER_HOST` with `SWAGGER_URL` to fix this problem.

I think, if your suggestion is applied,the developer will have to make two patterns test case for http://petstore.swagger.io and http://localhost:8002.
I think it is better to handle only one url.

Let me know if you have any questions.

**Comment by kazuhitoyokoi** [comment]
@HirokiUchikawa Good. 💯  Thank you for your investigation. Please ignore my suggestion and use environment variable, SWAGGER_URL instead of SWAGGER_HOST.

**Pull request merged**
