### PR TITLE
Updated 'Example 2' save function section

### PR DESCRIPTION
**Pull request by juggledad**
- [x] Documentation update
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Updated the README.md to expand on the 'Example 2' description of how to save the function node

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [x] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

**Comment by dceejay** [comment]
Thank - 

from the forum discussion - should it also include the `-n ...` name parameter in the command to ensure it works ? or does it pick up the name correctly ?

**Comment by juggledad** [comment]
As long as the 'Name' in the function node is filled in, it picks up that name for the final node name regardless of the name you save the file as. So If I called my function 'pauls function' and saved it as 'test.js', when you run the node-red-nodegen you end up with 'node-red-contrib-pauls-function'. 

If you leave the function's `name' option blank, you end up with 'node-red-contrib-unnamed-function'

In all case, if you use the '--name' option, like '--name fubar' you end up with node-red-contrib-fubar

**Comment by juggledad** [comment]
One oddity that I notice. In the function node - export item dropdown - 'Save to Library' is shows 

`Library -> function -> yourname.js`

but if you go look at the actual file path, the folder is function**s** (note it is plural).
The example shows the command to be:

`node-red-nodegen ~/.node-red/lib/function/lower-case.js`

which fails because the path needs it to use functions (plural) so somewhere it needs to change

**Comment by kazuhitoyokoi** [comment]
@juggledad Thank you for the notice. It was just typo which I created. I fixed it in the commit, https://github.com/node-red/node-red-nodegen/commit/9c761fee3e70308ae8490e57180062477b7072e7.

**Pull request merged**
